stages:
  - build

build_on_tag:
  stage: build
  image: maven:3.9.6-eclipse-temurin-17
  script:
    - echo "ğŸ·ï¸ Build avviata per il tag $CI_COMMIT_TAG"
    - mvn clean install -B
  only:
    - tags
